{
 "title": "HTTP Server Projeto Korp",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disponibilidade do serviço",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_projeto_korp_up" }
   ]
  },
  {
   "title": "Requisições / minuto",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_projeto_korp_requests_total[1m])) * 60"
    }
   ]
  },
  {
   "title": "Uptime em segundos",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_projeto_korp_uptime_seconds"
    }
   ]
  },
  {
   "title": "Volume de requisições",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_server_projeto_korp_requests_total[1m]))"
    }
   ]
  }
 ]
}