---
- name: Build da imagem da aplicação
  ansible.builtin.command: docker compose build
  args:
    chdir: "{{ project_dir }}"
  changed_when: true

- name: Subir containers com Docker Compose
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "{{ project_dir }}"
  register: compose_up
  changed_when: "'Started' in compose_up.stderr or 'Created' in compose_up.stderr"