---
project_name: http-server-projeto-korp
docker_network_name: korp_bridge
project_dir: "{{ playbook_dir }}/.."
deploy_user: "{{ ansible_facts['env']['SUDO_USER'] | default(ansible_facts['user_id']) }}"